apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  - image: redis
    name: redis
    ports:
    - containerPort: 6379